# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('used_memory', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('cpu_0', models.IntegerField()),
                ('cpu_1', models.IntegerField()),
                ('cpu_2', models.IntegerField()),
                ('cpu_3', models.IntegerField()),
                ('temp_0', models.IntegerField()),
                ('temp_1', models.IntegerField()),
                ('temp_2', models.IntegerField()),
                ('temp_3', models.IntegerField()),
            ],
            options={
                'db_table': 'data',
            },
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pc', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
                ('distro', models.CharField(max_length=100)),
                ('isa', models.CharField(max_length=100)),
                ('kernel', models.CharField(max_length=100)),
                ('cpu', models.CharField(max_length=100)),
                ('memory', models.FloatField()),
                ('ram', models.FloatField()),
                ('swap', models.FloatField()),
                ('high', models.FloatField()),
                ('crit', models.FloatField()),
            ],
            options={
                'db_table': 'computer',
            },
        ),
        migrations.AddField(
            model_name='data',
            name='id_pc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.PC'),
        ),
    ]
