# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20170721_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='fullData',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pc',
            name='limit',
            field=models.IntegerField(),
        ),
    ]
