# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 00:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_pc_fulldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 22, 0, 46, 39, 289713)),
        ),
    ]
