# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 00:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_data_date_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date_add',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
